/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operand {
	int num1;
	int num2;
};
typedef struct operand operand;

#define CALCULATOR_PROG 0x20171640
#define CALCULATOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(operand *, CLIENT *);
extern  int * add_1_svc(operand *, struct svc_req *);
#define sub 2
extern  int * sub_1(operand *, CLIENT *);
extern  int * sub_1_svc(operand *, struct svc_req *);
#define mul 3
extern  int * mul_1(operand *, CLIENT *);
extern  int * mul_1_svc(operand *, struct svc_req *);
#define div 4
extern  int * div_1(operand *, CLIENT *);
extern  int * div_1_svc(operand *, struct svc_req *);
#define pow 5
extern  int * pow_1(operand *, CLIENT *);
extern  int * pow_1_svc(operand *, struct svc_req *);
extern int calculator_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
#define sub 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define mul 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
#define pow 5
extern  int * pow_1();
extern  int * pow_1_svc();
extern int calculator_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operand (XDR *, operand*);

#else /* K&R C */
extern bool_t xdr_operand ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
