/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
add_1_svc(operand *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->num1 + argp->num2;

	return &result;
}

int *
sub_1_svc(operand *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->num1 - argp->num2;

	return &result;
}

int *
mul_1_svc(operand *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->num1 * argp->num2;

	return &result;
}

int *
div_1_svc(operand *argp, struct svc_req *rqstp)
{
	static int  result;

	if (argp->num2 != 0)
	    result = argp->num1 / argp->num2;
	else
	    result = (1 << 30);

	return &result;
}

int *
pow_1_svc(operand *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;

	result = 1;
	i = 0;

	while (i < argp->num2){
	    result *= argp-> num1;
	    i++;
	}

	return &result;
}
